version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis

  redis:
    image: "redis"
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    ports:
      - "$REDIS_PORT:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
volumes:
  redis-data:
